version: '3'

volumes:
  static:
  database:

services:
  note-k8s:
    build:
      context: .
      dockerfile: compose/production/django/Dockerfile
    image: note-k8s
    container_name: note-k8s
    working_dir: /app
    volumes:
      - database:/app/database
      - static:/app/static
    env_file:
      - .envs/.production
    ports:
      - "8000:8000"
    command: /start.sh

  nginx:
    build:
      context: .
      dockerfile: compose/production/nginx/Dockerfile
    image: note-k8s_nginx
    container_name: note-k8s_nginx
    volumes:
      - static:/apps/note-k8s/static
    ports:
      - "80:80"
      - "443:443"
